api = "0.10"

[buildpack]
id = "patbaumgartner/buildpacks-composite"
name = "Patbaumgartner Composite Buildpack"
version = "0.1.0"
keywords = ["spring-boot", "aot", "caching"]
description = "Composite buildpack containing only the AOT cache buildpack (builder already supplies Java)"
homepage = "https://github.com/patbaumgartner/talk-buildpacks-unpacked-custom-aot-caching"

[[buildpack.licenses]]
type = "Apache-2.0"

[[order]]

[[order.group]]
id = "patbaumgartner/buildpacks-ascii-weather"
version = "0.1.0"
optional = true

[[order.group]]
id = "patbaumgartner/buildpacks-aot-cache"
version = "0.1.0"
optional = true
